// Generated by BUCKLESCRIPT VERSION 3.1.5, PLEASE EDIT WITH CARE
'use strict';

var $$Array = require("bs-platform/lib/js/array.js");
var React = require("react");
var ReasonReact = require("reason-react/src/ReasonReact.js");

var component = ReasonReact.statelessComponent("Page");

function handleClick() {
  console.log("clicked!");
  return /* () */0;
}

var data = /* array */[
  /* record */[
    /* userame */"Matt",
    /* permission : Admin */0
  ],
  /* record */[
    /* userame */"Luke",
    /* permission : Worker */2
  ],
  /* record */[
    /* userame */"Jacob",
    /* permission : Worker */2
  ],
  /* record */[
    /* userame */"Mike",
    /* permission : User */1
  ],
  /* record */[
    /* userame */"Dave",
    /* permission : User */1
  ],
  /* record */[
    /* userame */"Dave",
    /* permission : User */1
  ]
];

function make(message, _) {
  return /* record */[
          /* debugName */component[/* debugName */0],
          /* reactClassInternal */component[/* reactClassInternal */1],
          /* handedOffState */component[/* handedOffState */2],
          /* willReceiveProps */component[/* willReceiveProps */3],
          /* didMount */component[/* didMount */4],
          /* didUpdate */component[/* didUpdate */5],
          /* willUnmount */component[/* willUnmount */6],
          /* willUpdate */component[/* willUpdate */7],
          /* shouldUpdate */component[/* shouldUpdate */8],
          /* render */(function () {
              return React.createElement("div", undefined, React.createElement("h1", {
                              onClick: (function () {
                                  console.log("clicked!");
                                  return /* () */0;
                                })
                            }, message), React.createElement("ul", undefined, $$Array.map((function (item) {
                                    var match = item[/* permission */1];
                                    var tmp;
                                    switch (match) {
                                      case 0 : 
                                          tmp = "Admin";
                                          break;
                                      case 1 : 
                                          tmp = "User";
                                          break;
                                      case 2 : 
                                          tmp = "Worker";
                                          break;
                                      
                                    }
                                    return React.createElement("li", undefined, React.createElement("div", undefined, item[/* userame */0], " - ", tmp), React.createElement("div", undefined));
                                  }), data)));
            }),
          /* initialState */component[/* initialState */10],
          /* retainedProps */component[/* retainedProps */11],
          /* reducer */component[/* reducer */12],
          /* subscriptions */component[/* subscriptions */13],
          /* jsElementWrapped */component[/* jsElementWrapped */14]
        ];
}

exports.component = component;
exports.handleClick = handleClick;
exports.data = data;
exports.make = make;
/* component Not a pure module */
